services:

    user_bundle.user:
        class:     UserBundle\Service\UserService
        arguments: ['@security.token_storage', '@security.authorization_checker']

    myproject_user.user_service:
        class: UserBundle\Handler\UserHandler
        arguments: ["@service_container", '%fos_user.model.user.class%']
